import type { Agent, Project } from '@/lib/db/schema';

// Agent color palette - assigned in order of creation
export const AGENT_COLORS = [
    '#FF0000', // red
    '#FF7F00', // orange
    '#0000FF', // blue
    '#4B0082', // indigo
    '#9400D3', // violet
    '#00FF00', // green
    '#FFFF00', // yellow
] as const;

// Get the next available color for a new agent
export function getNextAgentColor(existingColors: string[]): string {
    const usedColors = new Set(existingColors);
    return AGENT_COLORS.find((c) => !usedColors.has(c)) || AGENT_COLORS[0];
}

// Build the complete system prompt for an agent
export function buildAgentSystemPrompt(
    agent: Agent,
    project: Project,
    action?: 'chat' | 'report' | 'deep_think'
): string {
    const parts: string[] = [];

    // 1. Base identity section
    parts.push(`You are ${agent.name}. ${agent.description || ''}

${agent.systemPrompt}
`);

    // 2. Tool usage instructions
    const toolsEnabled = typeof agent.toolsEnabled === 'string'
        ? JSON.parse(agent.toolsEnabled) as string[]
        : agent.toolsEnabled || [];

    if (toolsEnabled.length > 0) {
        parts.push(`You have access to the following tools and should use them proactively:
`);

        if (toolsEnabled.includes('rag_search')) {
            parts.push(`- rag_search: Search through the project's documents. Use this whenever the user asks about topics that might be covered in the uploaded documents. Always search documents first before answering factual questions about the project content.
`);
        }

        if (toolsEnabled.includes('web_search')) {
            parts.push(`- web_search: Search the internet for current information. Use this when you need up-to-date data, recent events, or information not likely in the project documents.
`);
        }

        if (toolsEnabled.includes('rag_search') && toolsEnabled.includes('web_search')) {
            parts.push(`
You can use BOTH tools in a single response. For example, if asked to compare project data with industry trends, search the documents for project data AND search the web for industry trends, then synthesize.

When citing information from documents, always mention the source document name and page number.
When citing web results, include the source URL.
`);
        }
    }

    // 3. Action-specific instructions
    const actionsEnabled = typeof agent.actionsEnabled === 'string'
        ? JSON.parse(agent.actionsEnabled) as string[]
        : agent.actionsEnabled || [];

    if (actionsEnabled.includes('report')) {
        parts.push(`
When asked to generate a report, structure your response with clear sections, use data from both documents and web sources, and format with markdown headers, bullet points, and tables where appropriate.
`);
    }

    if (actionsEnabled.includes('deep_think')) {
        parts.push(`
When asked to think deeply or analyze something complex, break down your reasoning step by step. Show your thought process explicitly. Consider multiple perspectives and present your analysis before giving conclusions.
`);
    }

    // 4. Response style instruction
    parts.push(`
Format your responses with clean markdown. Use headers (##) for sections, bullet points for lists, and code blocks for technical content. When presenting data, use markdown tables. Be thorough but concise.
`);

    // 5. Action-specific prompt modifications
    if (action === 'deep_think') {
        parts.unshift(`Take your time with this. Think step by step. Show your reasoning process explicitly. Consider multiple angles before reaching conclusions.

`);
    }

    if (action === 'report') {
        parts.unshift(`The user has requested a formal report. Generate a comprehensive, well-structured report with the following format:

<!-- REPORT_START -->
# [Report Title]

**Generated by:** ${agent.name}
**Date:** ${new Date().toLocaleDateString()}
**Based on:** [Sources Used]

## Executive Summary
[Brief overview of findings]

## [Main Section 1]
[Detailed content with data]

## [Main Section 2]
[Detailed content with data]

## Key Findings
[Numbered list of findings]

## Recommendations
[Actionable recommendations]

## Sources
[List all document and web sources cited]
<!-- REPORT_END -->

IMPORTANT: You MUST use both rag_search and web_search tools extensively before writing the report. Search for all relevant information first, then synthesize into the report.

`);
    }

    // 6. Project context
    parts.push(`
You are working within the project "${project.name}". ${project.description || ''}
`);

    return parts.join('\n');
}

// Default system prompt for new agents
export const DEFAULT_SYSTEM_PROMPT = `You are a helpful AI assistant. You are knowledgeable, precise, and thorough.

When answering questions:
- Search available documents first for relevant information
- Use web search for current events or data not in documents
- Provide clear, well-structured responses
- Cite your sources when using information from documents or the web
- If you don't know something, say so honestly

Be concise but comprehensive. Focus on being genuinely helpful.`;
