'use client';

import { useState } from 'react';
import { Copy, Check } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { RichResponse } from './rich-response';
import { format } from 'date-fns';

interface ReportBlockProps {
    content: string;
    agentName?: string;
    agentColor?: string;
}

export function ReportBlock({ content, agentName = 'Agent', agentColor = '#FF7F00' }: ReportBlockProps) {
    const [copied, setCopied] = useState(false);

    const handleCopy = async () => {
        await navigator.clipboard.writeText(content);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    // Extract title from content (first # heading)
    const titleMatch = content.match(/^#\s+(.+)$/m);
    const title = titleMatch ? titleMatch[1] : 'Report';

    return (
        <div className="my-4 border border-black rounded-md overflow-hidden">
            {/* Accent strip */}
            <div className="h-1" style={{ backgroundColor: agentColor }} />

            {/* Header */}
            <div className="px-6 py-4 border-b border-gray-200">
                <h3 className="text-lg font-bold text-black">{title}</h3>
                <p className="text-sm text-gray-400 mt-1">
                    Generated by {agentName} • {format(new Date(), 'MMMM d, yyyy')}
                </p>
            </div>

            {/* Content */}
            <div className="px-6 py-4">
                <ReportContent content={content} />
            </div>

            {/* Actions */}
            <div className="px-6 py-3 border-t border-gray-200 flex gap-2">
                <Button
                    variant="outline"
                    size="sm"
                    className="border-black"
                    onClick={handleCopy}
                >
                    {copied ? (
                        <>
                            <Check className="h-4 w-4 mr-2" />
                            Copied
                        </>
                    ) : (
                        <>
                            <Copy className="h-4 w-4 mr-2" />
                            Copy to clipboard
                        </>
                    )}
                </Button>
                <Button
                    size="sm"
                    className="bg-black text-white"
                    disabled
                    title="Coming soon"
                >
                    Download as PDF
                </Button>
            </div>
        </div>
    );
}

function ReportContent({ content }: { content: string }) {
    // Remove the title since we already show it in the header
    const contentWithoutTitle = content.replace(/^#\s+.+$/m, '').trim();

    return (
        <div className="prose prose-sm max-w-none">
            <RichResponseInner content={contentWithoutTitle} />
        </div>
    );
}

// Simplified version that doesn't check for report markers (to avoid recursion)
function RichResponseInner({ content }: { content: string }) {
    return (
        <div className="text-black">
            {content.split('\n').map((line, i) => {
                // Headers
                if (line.startsWith('## ')) {
                    return <h2 key={i} className="text-lg font-bold mt-4 mb-2">{line.slice(3)}</h2>;
                }
                if (line.startsWith('### ')) {
                    return <h3 key={i} className="text-base font-bold mt-3 mb-1">{line.slice(4)}</h3>;
                }
                // Bold lines
                if (line.startsWith('**') && line.endsWith('**')) {
                    return <p key={i} className="font-bold mb-1">{line.slice(2, -2)}</p>;
                }
                // List items
                if (line.startsWith('- ') || line.startsWith('* ')) {
                    return <li key={i} className="ml-4 mb-1">{line.slice(2)}</li>;
                }
                if (line.match(/^\d+\.\s/)) {
                    return <li key={i} className="ml-4 mb-1">{line.replace(/^\d+\.\s/, '')}</li>;
                }
                // Empty line
                if (line.trim() === '') {
                    return <br key={i} />;
                }
                // Regular paragraph
                return <p key={i} className="mb-2">{line}</p>;
            })}
        </div>
    );
}
